[project]
name = "jira-analyzer"
version = "0.1.0"
description = """
Tool for automatic data collection and analysis of Jira task tracker with AI-driven qualitiy estimation.
""""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai>=2.31.0",
    "python-dotenv>=1.2.2",
]

[dependency-groups]
dev = [
    {include-group = "test"},
    {include-group = "lint"}
]
check = [
    {include-group = "test"},
    {include-group = "lint"}
]
lint = [
    "ruff>=0.15.10",
]
test = [
    "pytest>=9.0.3",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = "-v --tb=short"
markers = [
    "unit: unit tests",
    "integration: integration tests",
]